export const projects = [
  {
    id: 1,
    img: "https://i.ibb.co/pWPLJR6/website9.png",
    link: "https://allexandar93.github.io/learning-platform/",
    title: "Learning platform",
    codeLink: "https://github.com/Allexandar93/learning-platform",
  },

  {
    id: 2,
    img: "https://i.ibb.co/WcwwNxQ/website4.png",
    link: "https://allexandar93.github.io/landing-re/",
    title: "Real estate landing page",
    codeLink: "https://github.com/Allexandar93/landing-re",
  },
  {
    id: 3,
    img: "https://i.ibb.co/5FgXX9V/website6.png",
    link: "https://allexandar93.github.io/techecommerce/",
    title: "Ecommerce page with cart",
    codeLink: "https://github.com/Allexandar93/techecommerce",
  },
  {
    id: 4,
    img: "https://i.ibb.co/BwG2CTk/website5.png",
    link: "https://allexandar93.github.io/real-estate-page/",
    title: "Construction landing page",
    codeLink: "https://github.com/Allexandar93/real-estate-page",
  },
  {
    id: 5,
    img: "https://i.ibb.co/CzhjjvF/website8.png",
    link: "https://allexandar93.github.io/html-email-template/",
    title: "HTML email template",
    codeLink: "https://github.com/Allexandar93/html-email-template",
  },
  {
    id: 6,
    img: "https://i.ibb.co/rxCwbkf/website7.png",
    link: "https://allexandar93.github.io/trivia-app/",
    title: "To do list",
    codeLink: "https://github.com/Allexandar93/trivia-app",
  },
  {
    id: 7,
    img: "https://i.ibb.co/zFkCx4C/website3.png",
    link: "https://allexandar93.github.io/to-do-list/",
    title: "To do list",
    codeLink: "https://github.com/Allexandar93/to-do-list",
  },
  {
    id: 8,
    img: "https://i.ibb.co/g6hyqyB/website2.png",
    link: "https://allexandar93.github.io/form-validation/",
    title: "Form validator",
    codeLink: "https://github.com/Allexandar93/form-validation",
  },
  {
    id: 9,
    img: "https://i.ibb.co/GFmZsww/website1.png",
    link: "https://allexandar93.github.io/instagram-clone/",
    title: "Instagram clone",
    codeLink: "https://github.com/Allexandar93/instagram-clone",
  },
];
